export const FIND_ALL_MATCHES = [
  {
    matchDate: '2022-12-18',
    season: '2022-2023',
    competition: 'World Cup',
    home: false,
    team: 'Argentina',
    opponent: 'France',
    teamScore: 3,
    opponentScore: 3,
    goals: 2,
    assists: 0,
    started: true,
    minutesPlayed: 120,
    pensScored: 1,
    pensMissed: 0,
    hatTricks: 0,
    freeKicks: 0,
    insideBox: 1,
    outsideBox: 0,
    left: 1,
    right: 1,
    head: 0,
    other: 0,
    successfulDribbles: 0,
    motm: false,
  },
];

export const FIND_ALL_TOTALS = {
  totalGoals: 7,
  totalAssists: 3,
  totalMatches: 7,
  totalMinutes: 690,
  homeMatches: 0,
  awayMatches: 7,
  matchesWon: 4,
  matchesLost: 1,
  matchesStarted: 7,
  totalPensScored: 4,
  totalPensMissed: 1,
  totalHatTricks: 0,
  totalFreeKicks: 0,
  totalInsideBox: 2,
  totalOutsideBox: 1,
  totalLeft: 6,
  totalRight: 1,
  totalHeaded: 0,
  totalOtherBodyPart: 0,
  totalSuccessfulDribbles: 15,
  totalMotm: 2,
};
